config/routes.rb
Rails.application.routes.draw do
  resources :customers, only: [:index]

  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/customer_search_term.rb
class CustomerSearchTerm
	attr_reader :where_clause, :where_args, :order

	def initialize(search_term)
		search_term = search_term.downcase
		@where_clause = ""
		@where_args = {}
		if search_term =~ /@/
			build_for_email_search(search_term)
		else
			build_for_name_search(search_term)
		end
	end

	def build_for_name_search(search_term)
		@where_clause << case_insensitive_search(:first_name)
		@where_args[:first_name] = start_with(search_term)

		@where_clause << " OR #{case_insensitive_search(:last_name)}"
		@where_args[:last_name] = start_with(search_term)

		@order = "last_name asc"
	end

	def build_for_email_search(search_term)
		@where_clause << case_insensitive_search(:first_name)
		@where_args[:first_name] = start_with(extract_name(search_term))
		
		@where_clause << " OR #{case_insensitive_search(:last_name)}"
		@where_args[:last_name] = start_with(extract_name(search_term))

		@where_clause << " OR #{case_insensitive_search(:email)}"
		@where_args[:email] = search_term

		@order = "lower(email) = " + ActiveRecord::Base.connection.quote(search_term) + "desc, last_name asc"
	end

	def start_with(search_term)
		search_term + "%"
	end

	def case_insensitive_search(field_name)
		"lower(#{field_name}) like :#{field_name}"
	end

	def extract_name(email)
		email.gsub(/@.*$/,'').gsub(/[0-9]+/,'')
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	PAGE_SIZE = 10
  	def index
  		@page = (params[:page] || 0).to_i
  		if params[:keywords].present?
  			@keywords = params[:keywords]
  			customer_search_term = CustomerSearchTerm.new(@keywords)
  			@customers = Customer.where(customer_search_term.where_clause, customer_search_term.where_args).order(customer_search_term.order).offset(PAGE_SIZE * @page).limit(PAGE_SIZE)
  		else
  			@customers = []
  		end

        respond_to do |format|
            format.html {}
            format.json {render json: @customers}
        end
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Previous".html_safe, customers_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next">
			<%= link_to "Next &rarr;".html_safe, customers_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/customers/index.html.erb
<header>
	<h1>Customer Search</h1>
</header>

<section class="search-form">
	<%= form_for :customers, method: :get do |f| %>
		<div class="input-group input-group lg">
			<%= label_tag :keywords, nil, class: "sr-only" %>
			<%= text_field_tag :keywords, nil, placeholder: "First Name, Last Name, or Email Address", class: "form-control input-lg" %>
			<span class="input-group-btn">
				<%= submit_tag "Find Customers", class: "btn btn-primary btn-lg" %>
			</span>
		</div>
	<% end %>
</section>

<section class="search-results">
	<header>
		<h1 class="h3">Results</h1>
	</header>

	<%= render partial: "pager", locals: {keywords: @keywords, page: @page} %>

	<ol class="list-group">
		<% @customers.each do |customer| %>
			<li class="list-group-item clearfix">
				<h3 class="pull-right">
					<small class="text-uppercase">Joined</small>
					<%= l customer.created_at.to_date %>
				</h3>
				<h2 class="h3">
					<%= customer.first_name %> <%= customer.last_name %>
					<small><%= customer.username %></small>
				</h2>
				
				<h4><%= customer.email %></h4>
			</li>
		<% end %>
	</ol>

	<%= render partial: "pager", locals: {keywords: @keywords, page: @page} %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
    	<title>Shine</title>
    	<%= csrf_meta_tags %>

    	<%= stylesheet_link_tag    'application', media: 'all' %>
    	<%= javascript_include_tag 'application' %>
  	</head>

  	<body class="container">
  		<% if notice.present? %>
  			<section class="alert alert-info">
  				<%= notice %>
  			</section>
  		<% end %>

  		<% if alert.present? %>
  			<section class="alert alert-danger">
  				<%= alert %>
  			</section>
  		<% end %>

    	<%= yield %>
  	</body>
</html>

app/views/welcome/index.html.erb
<section>
	<p>
		Future home of Shine's Dashboard
	</p>
	<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</section>